services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    image: txtkeep:latest
    command: gunicorn txtkeep.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - ./static:/app/static  # Mount static directory
    environment:
      # - DEBUG=0
      # - DB_NAME=${DB_NAME}
      # - DB_USER=${DB_USER}
      # - DB_PASSWORD=${DB_PASSWORD}
      # - DB_HOST=${DB_HOST}
      # - DB_PORT=5432
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
    expose:
      - "8000"


  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static  # Mount static directory
    ports:
      - "80:80"
    depends_on:
      - django
