# Generated by Django 5.0 on 2025-01-18 16:35

import django.db.models.deletion
import uploader.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TxtFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(db_index=True, max_length=255)),
                ('file_content', models.TextField(db_index=True)),
                ('uuid', models.CharField(db_index=True, default=uploader.models.get_uuid, max_length=64, unique=True)),
                ('file_size', models.IntegerField()),
                ('file_path', models.FilePathField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
